# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class God < Formula
  desc "A vim-inspired TUI for managing supervisord processes"
  homepage "https://github.com/nicklasos/god"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicklasos/god/releases/download/v1.0.0/god_Darwin_x86_64.tar.gz"
      sha256 "c55c647335b54c3715ba298790a4f99ad1d7c10dcd13cd9f26d5285d55e798a9"

      def install
        bin.install "god"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicklasos/god/releases/download/v1.0.0/god_Darwin_arm64.tar.gz"
      sha256 "24a86d19a60b5753dbeef9544a244e0f6aace0e2f63a9c8addf48a128b2a436b"

      def install
        bin.install "god"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/god/releases/download/v1.0.0/god_Linux_x86_64.tar.gz"
      sha256 "9f6026fb5782d42a437faee4cf9b9a8d2a83980175743b65bda3e975201e8cf8"
      def install
        bin.install "god"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/god/releases/download/v1.0.0/god_Linux_arm64.tar.gz"
      sha256 "1ae75fb5d16252d7ac40cc89cef415718dea1a455e1f259f850f3b5ee1cf36a3"
      def install
        bin.install "god"
      end
    end
  end
end
