# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class God < Formula
  desc "A vim-inspired TUI for managing supervisord processes"
  homepage "https://github.com/nicklasos/god"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicklasos/god/releases/download/v1.0.1/god_Darwin_x86_64.tar.gz"
      sha256 "4acfba2df03704435bd5297ef41dfc587f6448e328b7f5eb5979a6a3fc664c49"

      def install
        bin.install "god"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicklasos/god/releases/download/v1.0.1/god_Darwin_arm64.tar.gz"
      sha256 "4f8252eb784e1f048f50f860e3962287472a23069b957b4761762851f641b458"

      def install
        bin.install "god"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/god/releases/download/v1.0.1/god_Linux_x86_64.tar.gz"
      sha256 "4a281fe528618d0cec8a9e32e62543da8fdbb903fe9db6f588d6c62c4548022a"
      def install
        bin.install "god"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/god/releases/download/v1.0.1/god_Linux_arm64.tar.gz"
      sha256 "5348253f1b287ef056b711ce9471897749c9051c3afd8302ce7f3c265721a479"
      def install
        bin.install "god"
      end
    end
  end
end
