# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosshit < Formula
  desc "A vim-inspired TUI for managing SSH config files"
  homepage "https://github.com/nicklasos/gosshit"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.1.1/gosshit_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "d9e2a3bcfa1134dd13424b381085b6acba8250cb52371e7a3df95124be21d067"

      def install
        bin.install "gosshit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.1.1/gosshit_1.1.1_Darwin_arm64.tar.gz"
      sha256 "51a71aa7317ee2bb534913a15eb93ce2cebd03ea54297c425713c5d8d6a0aebd"

      def install
        bin.install "gosshit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.1.1/gosshit_1.1.1_Linux_x86_64.tar.gz"
      sha256 "0158bb5d7fb568350ab92c731ced94082b809480258dc6a2adb4f429c0225722"
      def install
        bin.install "gosshit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.1.1/gosshit_1.1.1_Linux_arm64.tar.gz"
      sha256 "54e531226c3a51514de222c020613c5a31795d15e6eaeed21b5f95aa000660c6"
      def install
        bin.install "gosshit"
      end
    end
  end
end
