# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosshit < Formula
  desc "A vim-inspired TUI for managing SSH config files"
  homepage "https://github.com/nicklasos/gosshit"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.0.1/gosshit_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "e119fedabaeebe02d31b8f0b9e7259e66434932748c68167ba83d54038b634f4"

      def install
        bin.install "gosshit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.0.1/gosshit_1.0.1_Darwin_arm64.tar.gz"
      sha256 "66a7ebe2fff4326fe3a3e3e4c81486f99c67e6ee573d7820b8262cee8e9be0ba"

      def install
        bin.install "gosshit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.0.1/gosshit_1.0.1_Linux_x86_64.tar.gz"
      sha256 "f7663f9bb84ad1a1fd1b51f902c236d2f541ac5591c92697c9b325aa3b0d8109"
      def install
        bin.install "gosshit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicklasos/gosshit/releases/download/v1.0.1/gosshit_1.0.1_Linux_arm64.tar.gz"
      sha256 "9d49efddacc014008499c6787815a8326c1c9089a9248dfe4c18980d2e67206b"
      def install
        bin.install "gosshit"
      end
    end
  end
end
